In [1]:
import tensorflow as tf 
import numpy as np
import tensorflow_datasets as tfds

2023-06-25 14:42:22.541056: I tensorflow/core/util/port.cc:110] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2023-06-25 14:42:22.587630: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
/usr/local/lib/python3.8/dist-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [2]:
# dataset = tfds.load("oxford_flowers102", split='train', batch_size=1, shuffle_files=True)
dataset = tfds.load("oxford_flowers102", split='train', shuffle_files=True)

2023-06-25 14:42:25.109576: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:982] could not open file to read NUMA node: /sys/bus/pci/devices/0000:01:00.0/numa_node
Your kernel may have been built without NUMA support.
2023-06-25 14:42:25.117701: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:982] could not open file to read NUMA node: /sys/bus/pci/devices/0000:01:00.0/numa_node
Your kernel may have been built without NUMA support.
2023-06-25 14:42:25.119077: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:982] could not open file to read NUMA node: /sys/bus/pci/devices/0000:01:00.0/numa_node
Your kernel may have been built without NUMA support.
2023-06-25 14:42:25.122963: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:982] could not open file to read NUMA node: /sys/bus/pci/devices/0000:01:00.0/numa_node
Your kernel may have been built without NUMA support.
2023-06-25 14:42:25.124414: I tensorflow/compile

In [3]:
ds = dataset.take(-1)
for i in ds:
    print(i["image"].shape)

2023-06-25 14:42:26.156776: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_4' with dtype int64 and shape [1]
	 [[{{node Placeholder/_4}}]]
2023-06-25 14:42:26.157112: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_2' with dtype string and shape [1]
	 [[{{node Placeholder/_2}}]]


(500, 667, 3)
(500, 666, 3)
(670, 500, 3)
(500, 505, 3)
(500, 672, 3)
(500, 761, 3)
(667, 500, 3)
(500, 672, 3)
(500, 667, 3)
(617, 500, 3)
(500, 664, 3)
(750, 500, 3)
(500, 752, 3)
(501, 667, 3)
(500, 667, 3)
(693, 500, 3)
(545, 501, 3)
(500, 581, 3)
(500, 667, 3)
(500, 516, 3)
(500, 780, 3)
(667, 500, 3)
(667, 500, 3)
(701, 500, 3)
(500, 752, 3)
(500, 667, 3)
(500, 657, 3)
(500, 539, 3)
(500, 626, 3)
(500, 752, 3)
(500, 649, 3)
(500, 550, 3)
(627, 500, 3)
(547, 500, 3)
(500, 752, 3)
(500, 530, 3)
(500, 752, 3)
(544, 500, 3)
(597, 500, 3)
(500, 752, 3)
(500, 667, 3)
(500, 750, 3)
(500, 825, 3)
(500, 723, 3)
(500, 668, 3)
(500, 750, 3)
(500, 825, 3)
(538, 500, 3)
(500, 789, 3)
(500, 553, 3)
(667, 500, 3)
(500, 752, 3)
(500, 681, 3)
(587, 500, 3)
(500, 625, 3)
(500, 667, 3)
(500, 551, 3)
(500, 752, 3)
(641, 500, 3)
(500, 637, 3)
(500, 752, 3)
(666, 500, 3)
(501, 568, 3)
(500, 666, 3)
(648, 500, 3)
(735, 500, 3)
(500, 667, 3)
(667, 500, 3)
(500, 546, 3)
(500, 750, 3)
(500, 752, 3)
(500, 

In [11]:
import tf_flower_ds
ds_iter = tf_flower_ds.flower_img_iter()
ds_fet = ds_iter.__next__()
# print(ds_fet)

2023-06-25 14:43:29.471560: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_0' with dtype int32
	 [[{{node Placeholder/_0}}]]
2023-06-25 14:43:29.554555: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_1' with dtype string and shape [1]
	 [[{{node Placeholder/_1}}]]
2023-06-25 14:43:29.554881: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_0' with dtype string and shape [1]
	 [[{{node Placeholder

InvalidArgumentError: {{function_node __wrapped__IteratorGetNext_output_types_1_device_/job:localhost/replica:0/task:0/device:CPU:0}} TypeError: `generator` yielded an element that did not match the expected structure. The expected structure was (tf.int32,), but the yielded element was [[[1.        2.        0.       ]
  [1.        2.        0.       ]
  [1.        2.        0.       ]
  ...
  [1.        1.        1.       ]
  [1.        1.        1.       ]
  [1.        1.        1.       ]]

 [[1.        2.        0.       ]
  [1.        2.        0.       ]
  [1.        2.        0.       ]
  ...
  [1.        1.        1.       ]
  [1.        1.        1.       ]
  [1.        1.        1.       ]]

 [[1.        2.        0.       ]
  [1.        2.        0.       ]
  [1.        2.        0.       ]
  ...
  [1.        1.        1.       ]
  [1.        1.        1.       ]
  [1.        1.        1.       ]]

 ...

 [[1.        1.        1.       ]
  [1.        1.        1.       ]
  [1.        1.        1.       ]
  ...
  [6.        7.        2.       ]
  [6.        7.        2.       ]
  [5.151367  6.151367  1.1513672]]

 [[1.        1.        1.       ]
  [1.        1.        1.       ]
  [1.        1.        1.       ]
  ...
  [6.        7.        2.       ]
  [6.        7.        2.       ]
  [5.151367  6.151367  1.1513672]]

 [[1.        1.        1.       ]
  [1.        1.        1.       ]
  [1.        1.        1.       ]
  ...
  [6.        7.        2.       ]
  [6.        7.        2.       ]
  [5.151367  6.151367  1.1513672]]].
Traceback (most recent call last):

  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/data/ops/from_generator_op.py", line 204, in generator_py_func
    flattened_values = nest.flatten_up_to(output_types, values)

  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/data/util/nest.py", line 377, in flatten_up_to
    assert_shallow_structure(shallow_tree, input_tree)

  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/data/util/nest.py", line 278, in assert_shallow_structure
    raise TypeError(

TypeError: If shallow structure is a sequence, input must also be a sequence. Input has type: 'EagerTensor'.


The above exception was the direct cause of the following exception:


Traceback (most recent call last):

  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/ops/script_ops.py", line 267, in __call__
    ret = func(*args)

  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/autograph/impl/api.py", line 642, in wrapper
    return func(*args, **kwargs)

  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/data/ops/from_generator_op.py", line 206, in generator_py_func
    raise TypeError(

TypeError: `generator` yielded an element that did not match the expected structure. The expected structure was (tf.int32,), but the yielded element was [[[1.        2.        0.       ]
  [1.        2.        0.       ]
  [1.        2.        0.       ]
  ...
  [1.        1.        1.       ]
  [1.        1.        1.       ]
  [1.        1.        1.       ]]

 [[1.        2.        0.       ]
  [1.        2.        0.       ]
  [1.        2.        0.       ]
  ...
  [1.        1.        1.       ]
  [1.        1.        1.       ]
  [1.        1.        1.       ]]

 [[1.        2.        0.       ]
  [1.        2.        0.       ]
  [1.        2.        0.       ]
  ...
  [1.        1.        1.       ]
  [1.        1.        1.       ]
  [1.        1.        1.       ]]

 ...

 [[1.        1.        1.       ]
  [1.        1.        1.       ]
  [1.        1.        1.       ]
  ...
  [6.        7.        2.       ]
  [6.        7.        2.       ]
  [5.151367  6.151367  1.1513672]]

 [[1.        1.        1.       ]
  [1.        1.        1.       ]
  [1.        1.        1.       ]
  ...
  [6.        7.        2.       ]
  [6.        7.        2.       ]
  [5.151367  6.151367  1.1513672]]

 [[1.        1.        1.       ]
  [1.        1.        1.       ]
  [1.        1.        1.       ]
  ...
  [6.        7.        2.       ]
  [6.        7.        2.       ]
  [5.151367  6.151367  1.1513672]]].


	 [[{{node PyFunc}}]] [Op:IteratorGetNext]

2023-06-25 14:43:29.656296: W tensorflow/core/framework/op_kernel.cc:1818] INVALID_ARGUMENT: TypeError: `generator` yielded an element that did not match the expected structure. The expected structure was (tf.int32,), but the yielded element was [[[ 61.601562   65.60156    51.601562 ]
  [ 66.80469    69.90234    55.902344 ]
  [ 68.24805    70.24805    56.248047 ]
  ...
  [ 53.992188   44.992188    1.9921875]
  [ 73.46484    62.81836    21.464844 ]
  [115.88672   103.88672    65.58594  ]]

 [[ 61.45646    64.63672    53.09594  ]
  [ 65.40453    68.50219    54.9375   ]
  [ 66.31836    68.31836    54.557686 ]
  ...
  [ 58.330215   49.330215    6.3302155]
  [ 79.78344    69.136955   27.78344  ]
  [122.640625  110.640625   72.33984  ]]

 [[ 63.992233   67.001045   57.574265 ]
  [ 65.44545    68.026436   56.87709  ]
  [ 65.30664    67.30664    54.729607 ]
  ...
  [ 63.66234    54.66234    11.662338 ]
  [ 92.80356    82.157074   40.80356  ]
  [140.77344   128.77344    90.47266  ]]

 ...

 [[ 