In [1]:
import tensorflow as tf 
import numpy as np
import tensorflow_datasets as tfds

2023-06-25 08:24:48.778924: I tensorflow/core/util/port.cc:110] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2023-06-25 08:24:48.819300: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
/usr/local/lib/python3.8/dist-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [2]:
# dataset = tfds.load("oxford_flowers102", split='train', batch_size=1, shuffle_files=True)
dataset = tfds.load("oxford_flowers102", split='train', shuffle_files=True)

2023-06-25 08:24:51.268910: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:982] could not open file to read NUMA node: /sys/bus/pci/devices/0000:01:00.0/numa_node
Your kernel may have been built without NUMA support.
2023-06-25 08:24:51.276369: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:982] could not open file to read NUMA node: /sys/bus/pci/devices/0000:01:00.0/numa_node
Your kernel may have been built without NUMA support.
2023-06-25 08:24:51.278090: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:982] could not open file to read NUMA node: /sys/bus/pci/devices/0000:01:00.0/numa_node
Your kernel may have been built without NUMA support.
2023-06-25 08:24:51.281160: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:982] could not open file to read NUMA node: /sys/bus/pci/devices/0000:01:00.0/numa_node
Your kernel may have been built without NUMA support.
2023-06-25 08:24:51.282360: I tensorflow/compile

In [12]:
ds = dataset.take(4)
for i in ds:
    print(i["image"])

tf.Tensor(
[[[1 2 0]
  [1 2 0]
  [1 2 0]
  ...
  [1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 2 0]
  [1 2 0]
  [1 2 0]
  ...
  [1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 2 0]
  [1 2 0]
  [1 2 0]
  ...
  [1 1 1]
  [1 1 1]
  [1 1 1]]

 ...

 [[1 1 1]
  [1 1 1]
  [1 1 1]
  ...
  [6 7 2]
  [6 7 2]
  [5 6 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]
  ...
  [6 7 2]
  [6 7 2]
  [5 6 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]
  ...
  [6 7 2]
  [6 7 2]
  [5 6 1]]], shape=(500, 667, 3), dtype=uint8)
tf.Tensor(
[[[ 61  65  51]
  [ 65  69  55]
  [ 69  71  57]
  ...
  [ 57  48   5]
  [ 87  75  35]
  [121 109  71]]

 [[ 61  64  53]
  [ 64  68  54]
  [ 67  69  56]
  ...
  [ 63  54  11]
  [ 94  82  42]
  [128 116  78]]

 [[ 64  67  58]
  [ 65  68  57]
  [ 66  68  57]
  ...
  [ 70  61  18]
  [113 101  61]
  [147 135  97]]

 ...

 [[ 65  70  64]
  [ 67  72  66]
  [ 66  71  65]
  ...
  [ 16  17  12]
  [ 20  21  16]
  [ 20  21  16]]

 [[ 62  67  61]
  [ 64  69  63]
  [ 63  68  62]
  ...
  [ 16  17  12]
  [ 20  21  16]
  [ 20  21  16]]

 [[

2023-06-25 08:46:20.179008: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_3' with dtype int64 and shape [1]
	 [[{{node Placeholder/_3}}]]
2023-06-25 08:46:20.179426: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_2' with dtype string and shape [1]
	 [[{{node Placeholder/_2}}]]
